version: '3'

services:
  # postgres:
  #   image: 'postgres:9.5'
  #   volumes:
  #     - 'postgres:/var/lib/postgresql/data'
  #   environment:
  #     - POSTGRES_PASSWORD=postgres

  app:
    build: .
    # depends_on:
    #   - 'postgres'
    command: bundle exec rails s -b 0.0.0.0
    # command: bundle exec ruby ./lib/my_rack.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/notebook-api'
      - 'box:/box'

volumes:
  # postgres:
  box:
